### PR TITLE
Git Cheatsheet

### PR DESCRIPTION
**Pull request by nair-r**
Just practicing various Git commands :) Forked your repo to my GitHub a/c, cloned it to my local repo, added a file with some Git commands and definitions called 'Git_CheatSheet.txt' and committed them to my local repo, pushed the commits to my GitHub fork and now submitting a pull-request to your original repo to complete the circle 😄 Cheers!

### CODE REVIEW

**Comment by gkiar** [comment]
Hi @nair-r! This is really fantastic, thank you so much for your PR and willingness to contribute your lessons-learned back for others!

To continue your Github learning, why don't you update this file to be a table using [Github-Flavoured Markdown](https://guides.github.com/features/mastering-markdown/) formatting (an example can be found [here](https://github.com/brainhack101/docker-cheat-sheet)).

You'll notice that all commits on this branch of your fork will be automatically added to the open PR, so you won't need to re-open another. Once you've made your changes, feel free to pop back here and comment, to make sure I've seen the updates :)

Keep it up!

**Review by gkiar — CHANGES_REQUESTED** [review]
Changes as summarized in the comment

**Comment by nair-r** [comment]
Hi @gkiar - Thank you for the kind and encouraging words! :) I've gone ahead and converted the cheatsheet to Markdown and while I was at it, I created a Markdown cheatsheet called markdown_practice.md because it was way too fun. 😁 I'm not sure if it automatically added my commits to this PR, so let me know if I should do a new PR. Cheers!

**Comment by gkiar** [comment]
It should when you push! If it doesn't/didn't, then sure, how about you open a new PR :)

**Comment by nair-r** [comment]
@gkiar - Oops..my bad! Forgot to push to remote repo. Just did! :)

**Comment by gkiar** [comment]
This is hilarious and awesome- do you mind if I share this on our slack?? 😆

**Review by gkiar — APPROVED** [review]

**Comment by nair-r** [comment]
@gkiar haha - more fun learning that way. Sure, share away! :) Also, thanks for accepting the pull request.

**Pull request merged**
